# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

global:
  secrets:
    masterPassword: nubus

provisioningApi:
  connection:
    url: "http://provisioning-api"

scimServer:
  connection:
    url: "http://scim-server"
  auth:
    enabled: false
    oidcTokenUrl: "foo"
    realm: "bar"
    clientId: "stub-scim-api-username"

ldap:
  connection:
    host: "ldap-server"
  auth:
    bindDn: "cn=admin,dc=univention-organization,dc=intranet"
    existingSecret:
      name: ldap-server-credentials
      keyMapping:
        password: adminPassword
