# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

global:
  secrets:
    masterPassword: nubus

provisioningApi:
  connection:
    url: "http://provisioning-api"
  auth:
    username: "scim-client"
    password: "password"
    # existingSecret:
    #   name: provisioning-register-clients-json-secrets
    #   keyMapping:
    #     password: "scim-client.json"

scimServer:
  connection:
    url: "http://scim-dev-server:8080/"
  auth:
    enabled: false
    oidcTokenUrl: "foo"
    realm: "bar"
    clientId: "stub-scim-api-username"

ldap:
  connection:
    host: "ldap-server"
  auth:
    bindDn: "cn=admin,dc=univention-organization,dc=intranet"
    existingSecret:
      name: ldap-server-admin
      keyMapping:
        password: password

scimDevServer:
  config:
    # -- Hostname of the SCIM server
    hostname: testhost
