# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: {{ include "common.names.fullname" . | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" $ ) | nindent 4 }}
  {{- if .Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
data:
  LOG_LEVEL: {{ .Values.scimConsumer.config.logLevel | required ".Values.config.LogLevel is required" | quote }}
  PROVISIONING_API_USERNAME: {{ default (include "common.names.fullname" .) .Values.nubusProvisioning.auth.username }}
  PROVISIONING_API_BASE_URL: {{ required ".Values.nubusProvisioning.connection.url is required." .Values.nubusProvisioning.connection.url | quote }}
  MAX_ACKNOWLEDGEMENT_RETRIES: {{ required ".Values.nubusProvisioning.connection.maxAcknowledgementRetries is required." .Values.nubusProvisioning.connection.maxAcknowledgementRetries | quote }}
  SCIM_API_USERNAME: {{ required ".Values.scimServer.auth.username is required" .Values.scimServer.auth.username }}
