# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH


{{- if not (.Values.nubusProvisioning.auth.existingSecret).name }}
{{- /*
The password value is currently required in two places:

1. In the json secret needed to create the subscription with the provisioning-register-consumers job.

2. As a plain password value in a secret that can be mounted by the consumer pod.
*/}}
{{- $name := default (include "common.names.fullname" .) .Values.nubusProvisioning.auth.username }}
{{- $scimConsumerSubscriptionPassword := include "nubus-common.secrets.passwords.manage"
  (dict
    "secret" (include "nubus-common.secrets.name" (dict "defaultNameSuffix" "svc-portal-server" "context" .))
    "key" "password"
    "username" $name
    "providedValues" (list "nubusProvisioning.auth.password")
    "context" .
  )
}}

kind: "Secret"
apiVersion: "v1"
metadata:
  name: "{{ include "common.names.fullname" . }}"
  name: {{ include "nubus-common.secrets.name" (dict "existingSecret" .Values.nubusProvisioning.auth "defaultNameSuffix" "provisioning-subscription" "context" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ $name }}.json: |
    {
      "name": {{ $name | quote }},
      "realms_topics":
        [
          {"realm": "udm", "topic": "users/user"}
          {{- if .Values.scimConsumer.config.groupSync }}
          , {"realm": "udm", "topic": "groups/group"}
          {{- end }}
        ],
      "request_prefill": {{ .Values.scimConsumer.config.prefill }},
      "password": {{ $scimConsumerSubscriptionPassword | quote }}
    }

---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ include "nubus-common.secrets.name" (dict "defaultNameSuffix" "provisioning-credentials" "context" .) | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if (.Values.global.secrets).keep }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- if .Values.additionalAnnotations }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  # TODO: No idea how to support a keyMapping here. :unamused:
  username: {{ $name | quote }}
  password: {{ $scimConsumerSubscriptionPassword | quote }}

{{- end }}
