[project]
name = "scim-server"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.11",
    "httpx>=0.28.1"
]

[tool.uv.sources]
scim-udm-transformer-lib = { path = "../scim-udm-transformer-lib" }
