[project]
name = "scim-server"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "pydantic-settings>=2.8.1",
    "uvicorn>=0.34.0",
]

[tool.uv.sources]
scim-udm-transformer-lib = { path = "../scim-udm-transformer-lib" }
