# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

{{- if .Values.provisioning.enabled }}
---

apiVersion: "v1"
kind: ConfigMap
metadata:
  name: {{ printf "%s-provisioning-init" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.provisioning.extraLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.provisioning.extraLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.provisioning.extraAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.provisioning.extraAnnotations "context" . ) | nindent 4 }}
  {{- end }}

data:
  KEYCLOAK_URL: {{ include "scim-server.keycloak.url" . | quote }}
  UDM_API_URL: {{ include "scim-server.udm.url" . | quote }}

---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: {{ printf "%s-provisioning-env" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.provisioning.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.provisioning.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.provisioning.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
data:
  DEBUG: {{ .Values.provisioning.config.debug.enabled | quote }}
  DOMAIN: {{ .Values.global.domain | quote }}
  KEYCLOAK_USERNAME: {{ tpl .Values.provisioning.keycloak.auth.username . | quote }}
  KEYCLOAK_HOST: {{ include "scim-server.provisioning.keycloak.connection.host" . | quote }}
  KEYCLOAK_REALM: {{ include "scim-server.keycloak.realm" . | quote }}
  KEYCLOAK_URL: {{ include "scim-server.provisioning.keycloak.connection.baseUrl" . | quote }}
  UNIVENTION_KEYCLOAK_BOOTSTRAP_TEMP_DIR: "/tmp"
  UNIVENTION_KEYCLOAK_BOOTSTRAP_DEBUG_PAUSE_BEFORE_SCRIPT_START: {{ .Values.provisioning.config.debug.pauseBeforeScriptStart  | quote }}
  KEYCLOAK_APP_BASE_URL: {{ include "scim-server.provisioning.config.nubusBaseUrl" . | quote }}
  UDM_URL: {{ include "scim-server.udm.url" . | quote }}
  SCIM_API_CLIENT_ID: {{ .Values.oauth.clientId | quote }}

{{- if .Values.provisioning.user.create }}
---

apiVersion: "v1"
kind: ConfigMap
metadata:
  name: {{ printf "%s-provisioning-create-user" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.provisioning.extraLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.provisioning.extraLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.provisioning.extraAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.provisioning.extraAnnotations "context" . ) | nindent 4 }}
  {{- end }}

data:
  create-user.py: |
    #!/usr/bin/env python3
    import os
    from univention.admin.rest.client import UDM

    udm_url = os.environ.get("UDM_URL")
    udm_username = os.environ.get("UDM_USERNAME")
    udm_password = os.environ.get("UDM_PASSWORD")

    new_user_username = os.environ.get("CREATE_USER_NAME")
    new_user_password = os.environ.get("CREATE_USER_PASSWORD")

    udm_client = UDM.http(udm_url, udm_username, udm_password)
    module = udm_client.get("users/user")

    results = list(module.search(f"uid={new_user_username}"))
    if results:
        for result in results:
            udm_obj = result.open()
            print(f"Deleting existing user: {udm_obj.properties['username']}")
            udm_obj.delete()

    udm_obj = module.new()
    udm_obj.properties["username"] = new_user_username
    udm_obj.properties["password"] = new_user_password
    udm_obj.properties["firstname"] = 'SCIM'
    udm_obj.properties["lastname"] = 'API'

    udm_obj.save()
    print(f"Created scim user user: {udm_obj.properties['username']}")

{{- end }}
{{- end }}
