# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
---
{{- $name := include "common.names.fullname" . }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" $ ) | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.additionalLabels "context" $ ) | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
        checksum/config-init: {{ include (print $.Template.BasePath "/configmap-init.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" $ ) | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ $name }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- $imagePullSecrets := coalesce .Values.global.imagePullSecrets }}
      {{- if $imagePullSecrets }}
      imagePullSecrets:
        {{- range $imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
      {{- end }}
      initContainers:
        - name: "wait-for-keycloak"
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext:
            {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          image: "{{ coalesce .Values.scimServer.waitForDependency.image.registry .Values.global.imageRegistry }}/{{ .Values.scimServer.waitForDependency.image.repository }}{{ if .Values.scimServer.waitForDependency.image.sha256 }}@sha256:{{ .Values.scimServer.waitForDependency.image.sha256 }}{{ else }}:{{ .Values.scimServer.waitForDependency.image.tag }}{{ end }}"
          imagePullPolicy: {{ coalesce .Values.scimServer.waitForDependency.image.imagePullPolicy .Values.global.imagePullPolicy | quote }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-init" (include "common.names.fullname" .) }}
          command: ["/bin/sh", "-c"]
          args:
          - >
            wait-for-keycloak.py
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: "wait-for-udm"
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext:
            {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          image: "{{ coalesce .Values.scimServer.waitForDependency.image.registry .Values.global.imageRegistry }}/{{ .Values.scimServer.waitForDependency.image.repository }}{{ if .Values.scimServer.waitForDependency.image.sha256 }}@sha256:{{ .Values.scimServer.waitForDependency.image.sha256 }}{{ else }}:{{ .Values.scimServer.waitForDependency.image.tag }}{{ end }}"
          imagePullPolicy: {{ coalesce .Values.scimServer.waitForDependency.image.imagePullPolicy .Values.global.imagePullPolicy | quote }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-init" (include "common.names.fullname" .) }}
          env:
            - name: UDM_API_USERNAME
              value: {{ required "is required" .Values.udm.auth.username | quote }}
            - name: UDM_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "nubus-common.secrets.name" (dict "existingSecret" .Values.udm.auth.existingSecret "defaultNameSuffix" "udm-secret" "context" .) | quote }}
                  key: {{ include "nubus-common.secrets.key" (dict "existingSecret" .Values.udm.auth.existingSecret "key" "password") | quote }}
          command: ["/bin/sh", "-c"]
          args:
          - >
            wait-for-udm.sh
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      containers:
        - name: "scim-server"
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext:
            {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          image: "{{ coalesce .Values.scimServer.image.registry .Values.global.imageRegistry }}/{{ .Values.scimServer.image.repository }}{{ if .Values.scimServer.image.sha256 }}@sha256:{{ .Values.scimServer.image.sha256 }}{{ else }}:{{ .Values.scimServer.image.tag }}{{ end }}"
          imagePullPolicy: {{ coalesce .Values.scimServer.image.imagePullPolicy .Values.global.imagePullPolicy | quote }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-env" (include "common.names.fullname" .) }}
          env:
            - name: UDM_USERNAME
              value: {{ required "is required" .Values.udm.auth.username | quote }}
            - name: UDM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "nubus-common.secrets.name" (dict "existingSecret" .Values.udm.auth.existingSecret "defaultNameSuffix" "udm-secret" "context" .) | quote }}
                  key: {{ include "nubus-common.secrets.key" (dict "existingSecret" .Values.udm.auth.existingSecret "key" "password") | quote }}
            {{- with .Values.extraEnvVars }}
              {{- . | toYaml | nindent 14 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe: {{- omit .Values.probes.liveness "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe: {{- omit .Values.probes.readiness "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.startup.enabled }}
          startupProbe: {{- omit .Values.probes.startup "enabled" | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            {{- if .Values.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" .) | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.extraVolumes }}
          {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumes  "context" .) | nindent 8 }}
        {{- end }}
