# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
{{- if .Values.ingress.enabled }}
---
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  annotations:
    {{- if or .Values.ingress.annotations .Values.additionalAnnotations }}
    {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.ingress.annotations .Values.additionalAnnotations ) "context" . ) }}
    {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.certManager.enabled }}
    cert-manager.io/{{ .Values.ingress.certManager.issuerRef.kind | kebabcase }}: "{{ coalesce .Values.global.certManagerIssuer .Values.ingress.certManager.issuerRef.name }}"
    {{- end }}
spec:
  ingressClassName: {{ required ".Values.ingress.ingressClassName or .Values.global.ingressClass must be defined." ( coalesce .Values.ingress.ingressClassName .Values.global.ingressClass ) | quote }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ tpl .Values.ingress.host . | quote }}
      secretName: {{ coalesce .Values.ingress.tls.secretName (printf "%s-tls" (include "common.names.fullname" .)) | quote }}
  {{- end }}
  rules:
    - host: {{ required "The hostname has to be set in \"ingress.host\"." (tpl .Values.ingress.host .) | quote }}
      http:
        paths:
          - path: /scim/v2/
            pathType: ImplementationSpecific
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" $) "servicePort" "http" "context" $) | nindent 14 }}
          - path: /docs
            pathType: ImplementationSpecific
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" $) "servicePort" "http" "context" $) | nindent 14 }}
          - path: /openapi.json
            pathType: ImplementationSpecific
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" $) "servicePort" "http" "context" $) | nindent 14 }}
{{- end }}
