# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2024 Univention GmbH
{{- if .Values.setup.user.create }}
{{- $setupUserPassword := include "nubus-common.secrets.passwords.manage"
  (dict
    "secret" (include "nubus-common.secrets.name" (dict "defaultNameSuffix" "setup-create-user-secret" "context" .))
    "key" "password"
    "username" .Values.setup.user.username
    "providedValues" (list "setup.user.password")
    "context" .
  )
}}
---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ include "nubus-common.secrets.name" (dict "defaultNameSuffix" "setup-create-user-secret" "context" .) }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" $ ) | nindent 4 }}
  {{- if $.Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.additionalAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
stringData:
  new_user_password: {{ $setupUserPassword | quote }}
{{- end }}
