# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2024 Univention GmbH

{{- if .Values.provisioning.user.create }}

---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ printf "%s-provisioning-create-user-secret" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if $.Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.additionalLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if $.Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.additionalAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
stringData:
  new_user_username: {{ .Values.provisioning.user.username | quote }}
  new_user_password: {{ .Values.provisioning.user.password | quote }}
  new_group_name: {{ .Values.provisioning.user.group.name | quote }}

{{- end }}
