# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2024 Univention GmbH
{{- if not (.Values.udm.auth.existingSecret).name }}
{{- $name := default (include "common.names.fullname" .) .Values.udm.auth.username }}
{{- $udmPassword := include "nubus-common.secrets.passwords.manage"
  (dict
    "secret" (include "nubus-common.secrets.name" (dict "defaultNameSuffix" "udm-secret" "context" .))
    "key" "password"
    "username" $name
    "providedValues" (list "udm.auth.password")
    "context" .
  )
}}
---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ include "nubus-common.secrets.name" (dict "defaultNameSuffix" "udm-secret" "context" .) }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" $ ) | nindent 4 }}
  annotations:
    {{- if (.Values.global.secrets).keep }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- if .Values.additionalAnnotations }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
    {{- end }}
stringData:
  password: {{ $udmPassword | quote }}
{{- end }}
