# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
global:
  secrets:
    masterPassword: stub-secret

nubusProvisioning:
  connection:
    url: "http://nubus-provisioning-api"

scimServer:
  auth:
    username: "stub-scim-api-username"
