# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
global:
  secrets:
    masterPassword: stub-secret

nubusProvisioning:
  connection:
    url: "http://stub-nubus-provisioning-api"

scimServer:
  connection:
    url: "http://stub-scim-server"
  auth:
    oidcTokenUrl: "foo"
    clientId: "stub-scim-api-username"
    username: "stub-scim-api-username"

ldap:
  connection:
    uri: "ldap://stub-ldap-server"
  auth:
    bindDn: "uid=stub,cn=users,dc=univention-organization,dc=intranet"
    existingSecret:
      name: stub-ldap-server-credentials
