[project]
name = "udm-to-scim-sync"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
]

[tool.uv.sources]
scim-udm-transformer-lib = { path = "../scim-udm-transformer-lib" }
