# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

services:
  core:
    image: yuzutech/kroki
    depends_on:
      - mermaid
    environment:
      - KROKI_MERMAID_HOST=mermaid
    ports:
      - "8000:8000"
  mermaid:
    image: yuzutech/kroki-mermaid
    ports:
      - "8002:8002"
#  bpmn:
#    image: yuzutech/kroki-bpmn
#    ports:
#      - "8003:8003"
#  excalidraw:
#    image: yuzutech/kroki-excalidraw
#    ports:
#      - "8004:8004"
