#!/bin/bash

docker compose up -d
echo "-------------------"

path_with_ext="$1"
path_no_ext="${path_with_ext%.*}"
tmp_path="$(mktemp)"
function finish {
  rm -f "$tmp_path"
}
trap finish EXIT

python3 -c "import sys; import base64; import zlib; print(base64.urlsafe_b64encode(zlib.compress(sys.stdin.read().encode('utf-8'), 9)).decode('ascii'))" < "$path_with_ext" > "$tmp_path"
curl "http://127.0.0.1:8000/mermaid/png/$(<$tmp_path)" -o "$path_no_ext.png"

echo "-------------------"
ls -l "$path_with_ext" "$path_no_ext.png"
echo "-------------------"
echo "You may want to run: docker compose down -v"
