# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

{{- $_ := required "A SCIM server password is required, see parameter scimServer.auth." (coalesce .Values.scimServer.auth.password (.Values.scimServer.auth.existingSecret).name) }}
{{- if not (.Values.scimServer.auth.existingSecret).name }}
{{- $name := include "nubus-common.secrets.name" (dict "defaultNameSuffix" "scim-server" "context" .) | quote -}}
---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ $name }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
type: Opaque
stringData:
  password: {{ include "nubus-common.secrets.passwords.manage"
  (dict
    "secret" $name
    "key" "password"
    "username" "scim-client-scim-server"
    "providedValues" (list "scimServer.auth.password")
    "context" .
  )
| quote }}
{{- end }}
