# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "{{ include "common.names.fullname" . }}"
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" $ ) | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - name: scim-dev-server
      port: 8080
      # targetPort: 8080
      protocol: TCP
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
