sequenceDiagram
  actor SCIM Client
  participant SCIM REST as «REST»<br/>SCIM
  participant PostgreSQL

  SCIM Client ->>+ SCIM REST: GET (SCIM)
  SCIM REST ->>+ PostgreSQL: SQL
  PostgreSQL -->>- SCIM REST: SQL
  SCIM REST -->>- SCIM Client: SCIM object
