# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

services:
  test:
    image: gitregistry.knut.univention.de/univention/dev/nubus-for-k8s/common-helm/testrunner:0.27.0
    pull_policy: always
    command: |
      bash -c  "helm dependency build helm/scim-server/ &&
      helm dependency build helm/scim-server/ &&
      pytest tests/helm_unit"
    profiles:
      - test
    volumes:
      - "../helm/:/app/helm/"
      - "../tests/:/app/tests"

  test-chart-scim-client:
    image: gitregistry.knut.univention.de/univention/dev/nubus-for-k8s/common-helm/testrunner:0.27.0
    pull_policy: "if_not_present"
    command: "pytest tests/helm/chart"
    volumes:
      - "../helm/:/app/helm/"
      - "../tests/helm_unit/scim_client:/app/tests/helm/chart"

  test-chart-scim-server:
    image: gitregistry.knut.univention.de/univention/dev/nubus-for-k8s/common-helm/testrunner:0.27.0
    pull_policy: "if_not_present"
    command: "pytest tests/helm/chart"
    volumes:
      - "../helm/:/app/helm/"
      - "../tests/helm_unit/scim_server:/app/tests/helm/chart"
