# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

services:
  test:
    image: gitregistry.knut.univention.de/univention/dev/nubus-for-k8s/common-helm/testrunner:0.18.0
    pull_policy: always
    command: |
      bash -c  "helm dependency build helm/scim-server/ &&
      helm dependency build helm/scim-server/ &&
      pytest tests/helm_unit"
    profiles:
      - test
    volumes:
      - "../helm/:/app/helm/"
      - "../tests/:/app/tests"
