# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
---
global:
  ingressClass: "nginx"
  domain: "univention.test"

keycloak:
  connection:
    url: "https://keycloak.univention.test"
    realm: "nubus"

udm:
  connection:
    url: "https://udm.univention.test"

config:
  corsOrigins: '["https://scim.univention.test"]'

ingress:
  host: "scim.example.test"
  tls:
    secretName: "scim-server-tls"

setup:
  enabled: true
  config:
    nubusBaseUrl: "https://scim.univention.test"
  keycloak:
    auth:
      username: "stub_username"
    connection:
      baseUrl: "keycloak"
      host: "keycloak"
      port: 123
  user:
    create: true
    username: "scim-api"
