# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
global:
  ingressClass: "nginx"

udm:
  auth:
    password: "stub-password"

config:
  keycloak:
    url: "https://keycloak.univention.test"
  udm:
    url: "https://udm.univention.test"

ingress:
  host: "scim.example.test"
  tls:
    secretName: "scim-server-tls"
